Add `prefer-https` rule
sindresorhus/eslint-plugin-unicorn pull request #1084
Opened 2021-01-29 01:40 UTC by himynameisdave

Adds `prefer-https` rule.

Checks string literals, as well as comments.

⚠️  WIP, still need to support things like `http://localhost` ([see comment](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/971#issuecomment-768069994)), so I'll be editing the regex to handle this.

Resolves #971

2021-01-31 01:20 UTC, himynameisdave commented
I set the [`meta.type`](https://eslint.org/docs/developer-guide/working-with-rules#rule-basics) to `'problem'`, not sure if it should be `'suggestion'` instead though.

2021-02-01 14:41 UTC, sindresorhus requested changes

2021-02-01 14:41 UTC, sindresorhus commented on docs/rules/prefer-https.md
> +Enforce using HTTPS URLs over HTTP.
This should describe in what places this is enforced.

2021-02-01 14:41 UTC, sindresorhus commented on rules/prefer-https.js
> +const containsHttp = nodeValue => /http:\/\/(www\.)?[\w#%+.:=@~-]{2,256}\.[a-z]{2,4}\b([\w#%&+./:=?@~-]*)/.test(nodeValue);
We don't need to match more after the TLD.

2021-02-01 14:41 UTC, sindresorhus commented on rules/prefer-https.js
> +		const fixed = node.value.replace('http', 'https');
What if the comment is `// Foo bar http is good: https://asdasd.com`?

I think just replacing `http` substring is too fragile.

2021-02-01 14:41 UTC, sindresorhus commented on rules/prefer-https.js
> +		type: 'problem',
This is not correct.

2021-02-01 14:41 UTC, sindresorhus commented on test/prefer-https.js
> +});
You need to add a *lot* more tests.

2021-02-18 08:40 UTC, fisker commented
Is it possible to disable this rule on comments? Just a question, I never disabled problems in comments.

```js
// eslint-disable-next-line
// http://www.example.com
````

2021-02-21 00:35 UTC, himynameisdave commented
Hi @sindresorhus.

I've addressed your comments but am still struggling with the tests. They are currently failing in CI due to some weird module error: `'import' and 'export' may appear only with 'sourceType: module'` (see [here](https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1084/checks?check_run_id=1943974197)).

In general I found it quite difficult to debug this new rule, specifically debugging the output of the `fix`. Not sure what your prescribed method for debugging this would be, but usually for an eslint rule I would just run `eslint ./some-test-file.js --fix` to understand what's happening, although we don't seem to use eslint in that way for `run-rules-on-codebase`.

Another roadblock that I have run into is that, because of the nature of this rule, I needed to disable the rule on the test (because the test cases were being flagged when running `run-rules-on-codebase`). However when I then went to run `npm test`, it complains that there is no definition for the rule!?

All this to say is that I am happy to continue working on this rule, but I am will need some guidance as this is non-obvious to me. It feels much like I am coding in the dark, unable to easily debug what is happening when my rule is run (as well as how the infrastructure that is used to run the tests in this codebase actually works).

2021-03-22 09:11 UTC, sindresorhus commented
> They are currently failing in CI due to some weird module error: 'import' and 'export' may appear only with 'sourceType: module' (see here).

You need to rename the file extension to `.mjs`.

2021-03-22 09:11 UTC, sindresorhus commented
@fisker can probably give you some tips on debugging `fix`.

2021-03-23 03:16 UTC, fisker commented
You can disable it run on codebase by adding it [here](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/c5a43459e881d36e1aa79a7e41a0ec0a05b7e7b7/test/run-rules-on-codebase/lint.mjs#L23), we can enable it when `xo` updated.

2021-03-23 03:22 UTC, fisker commented
> It feels much like I am coding in the dark

I'm sorry it makes you feel bad, but `run-rules-on-codebase` is not a required step during implementing, it only need to be done before merge, mentioned in last step here https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/new-rule.md

2021-06-03 19:38 UTC, sindresorhus commented
@himynameisdave Still interested in finishing this? :)

2021-06-07 17:35 UTC, himynameisdave commented
@sindresorhus yep I'm still interested, although happy to hand this off to someone else if they have more time to work on it. 👍

2021-10-04 07:44 UTC, sindresorhus commented
Closing this to let someone else be able to continue it: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/971#issuecomment-933228408

2021-10-04 07:44 UTC, closed without merging