Add `prefer-array-flat` rule
sindresorhus/eslint-plugin-unicorn pull request #1126
Opened 2021-02-22 16:31 UTC by fisker

Fixes #975

2021-02-22 17:10 UTC, fisker commented
Half code in this rule just esquery selector. :smile:

2021-02-22 19:32 UTC, sindresorhus requested changes

2021-02-22 19:32 UTC, sindresorhus commented on docs/rules/prefer-array-flat.md
> +ES2019 introduced a new method [`Array#flat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) that flattens arrays, and there's a [`depth` parameter](ht
I don't think the `depth` parameter is relevant. People can read about it when they click the MDN link.

2021-02-22 19:32 UTC, sindresorhus commented on index.js
> +				// TODO[@fisker]: Set to `off` before merge
Don't forget this.

2021-02-23 01:34 UTC, fisker commented
Added a `functions` option, I think this can be useful https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1126/commits/43e53805541b60a7692574c222ec927f946d874d

2021-02-23 02:03 UTC, fisker commented
CI failure should not related, I'll look into it.

2021-02-23 06:16 UTC, sindresorhus commented on docs/rules/prefer-array-flat.md
> +}
I think our config examples should be in JS, not JSON.

2021-02-24 06:36 UTC, merged