Add `prefer-node-protocol` rule
sindresorhus/eslint-plugin-unicorn pull request #1203
Opened 2021-04-22 07:30 UTC by fisker

Fixes #1198

2021-04-22 08:03 UTC, sindresorhus requested changes

2021-04-22 08:03 UTC, sindresorhus commented on docs/rules/prefer-node-protocol.md
> +# Prefer use `node:` protocol when importing Node.js builtin modules
```suggestion
# Prefer using the `node:` protocol when importing Node.js builtin modules
```

2021-04-22 08:45 UTC, merged

2021-04-22 08:52 UTC, fisker commented
CI seems not running.

2021-04-22 09:04 UTC, sindresorhus commented
GH Actions is currently under cryptocurrency attacks. I think that might be related.

https://github.com/search?q=%22Demo+title+Add+files+via+upload%22+is:pr+user:sindresorhus&type=issues

2021-05-06 10:30 UTC, rubiin commented
how to use this type of import in typescript? Am I missing something. Using nodejs V14+

2021-05-06 10:54 UTC, sindresorhus commented
@rubiin This is not the place to ask TypeScript questions. Try https://github.com/microsoft/TypeScript/issues