Add `no-array-method-this-argument` rule
sindresorhus/eslint-plugin-unicorn pull request #1357
Opened 2021-06-16 08:50 UTC by fisker

Fixes #974

2021-06-16 08:56 UTC, fisker commented on test/snapshots/no-array-method-this-argument.mjs.md
> +      1 | array.map(callback.bind(thisArgument))␊
I didn't auto-fix this case to use `callback.bind`, since it's not the best option, people may won't get attention with auto-fix.

2021-06-17 07:29 UTC, sindresorhus requested changes

2021-06-17 07:29 UTC, sindresorhus commented on docs/rules/no-array-method-this-argument.md
> +# Forbid using this argument in array methods
```suggestion
# Disallow using the `this` argument in array methods
```

2021-06-17 07:29 UTC, sindresorhus commented on docs/rules/no-array-method-this-argument.md
> +Forbid using the `thisArg` argument in array methods:
```suggestion
The rule forbids using the `thisArg` argument in array methods:
```

2021-06-17 07:29 UTC, sindresorhus commented on rules/no-array-method-this-argument.js
> +	[SUGGESTION_BIND]: 'Use bound function.'
```suggestion
	[SUGGESTION_BIND]: 'Use a bound function.'
```

2021-06-17 11:18 UTC, merged