`no-array-callback-reference`: Ignore jQuery methods
sindresorhus/eslint-plugin-unicorn pull request #1457
Opened 2021-07-28 21:13 UTC by pustovalov

Fixes https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1376

2021-07-31 10:36 UTC, sindresorhus approved these changes

2021-08-02 02:07 UTC, fisker requested changes

2021-08-02 02:07 UTC, fisker commented on rules/no-array-callback-reference.js
> +			if (node.callee.object.callee && isNodeMatches(node.callee.object.callee, ignoredCallee)) {
```suggestion
			if (node.callee.object.type === 'CallExpression' && isNodeMatches(node.callee.object.callee, ignoredCallee)) {
```

2021-08-02 02:07 UTC, fisker commented on rules/no-array-callback-reference.js
> +	'$',
```suggestion
	'$',
	'jQuery',
```

2021-08-02 08:23 UTC, fisker approved these changes
Nice work!

2021-08-02 08:46 UTC, merged