Add `relative-url-style` rule
sindresorhus/eslint-plugin-unicorn pull request #1672
Opened 2021-12-29 10:38 UTC by fisker

Fixes #1614

2021-12-30 23:45 UTC, sindresorhus requested changes

2021-12-30 23:45 UTC, sindresorhus commented on rules/relative-url-style.js
> +	[MESSAGE_ID_NEVER]: 'Remove `./` prefix from the relative url.',
```suggestion
	[MESSAGE_ID_NEVER]: 'Remove the `./` prefix from the relative URL.',
```

2021-12-30 23:45 UTC, sindresorhus commented on rules/relative-url-style.js
> +			description: 'Enforce consistent relative url style.',
```suggestion
			description: 'Enforce consistent relative URL style.',
```

2021-12-30 23:45 UTC, sindresorhus commented on rules/relative-url-style.js
> +	[MESSAGE_ID_ALWAYS]: 'Use `./` prefix in the relative url.',
```suggestion
	[MESSAGE_ID_ALWAYS]: 'Add a `./` prefix to the relative URL.',
```

?

2021-12-30 23:45 UTC, sindresorhus commented on readme.md
> +| [relative-url-style](docs/rules/relative-url-style.md) | Enforce consistent relative url style. | ✅ | 🔧 |  |
```suggestion
| [relative-url-style](docs/rules/relative-url-style.md) | Enforce consistent relative URL style. | ✅ | 🔧 |  |
```

2021-12-31 01:28 UTC, fisker commented on docs/rules/relative-url-style.md
> +  - Always add a `./` prefix to the relative URL when possible.
`markdownlint` enforce to use space.

2021-12-31 10:58 UTC, merged