Add `no-typeof-undefined` rule
sindresorhus/eslint-plugin-unicorn pull request #1966
Opened 2022-11-17 07:43 UTC by fisker

Fixes #1492

2022-11-17 08:02 UTC, fisker commented on rules/no-typeof-undefined.js
> +					}
Same as https://github.com/sindresorhus/eslint-plugin-unicorn/blob/e4aaa42a780e2b155fa25fcba457162308dec36b/rules/no-negated-condition.js#L105, but I'm not going to make a reusable function in this PR, will do later.

2022-11-19 13:45 UTC, sindresorhus requested changes

2022-11-19 13:45 UTC, sindresorhus commented on docs/rules/no-typeof-undefined.md
> +# Enforce compare with `undefined` directly
```suggestion
# Disallow comparing `undefined` using `typeof`
```

2022-11-19 13:45 UTC, sindresorhus commented on docs/rules/no-typeof-undefined.md
> +Enforce compare value with `undefined` directly instead of compare `typeof value` with `'undefined'`.
```suggestion
Checking if a value is `undefined` by using `typeof value === 'undefined'` is needlessly verbose. It's generally better to compare against `undefined` directly. The only time `typeof` is needed is when a global variable potentially does not exists, in which case, using `globalThis.value === undefined` may be better.
```

2022-11-19 13:45 UTC, sindresorhus commented on docs/rules/no-typeof-undefined.md
> +This rule ignores variables not defined in file by default.
```suggestion
The rule ignores variables not defined in the file by default.
```

2022-11-19 13:45 UTC, sindresorhus commented on rules/no-typeof-undefined.js
> +	[MESSAGE_ID_ERROR]: 'Compare with `undefined` directly instead of `typeof` check.',
```suggestion
	[MESSAGE_ID_ERROR]: 'Compare with `undefined` directly instead of using `typeof`.',
```

2022-11-20 16:39 UTC, merged