Add `prefer-number-properties` rule
sindresorhus/eslint-plugin-unicorn pull request #622
Opened 2020-03-20 10:38 UTC by fisker

Fixes #594

2020-03-22 07:11 UTC, sindresorhus requested changes

2020-03-22 07:11 UTC, sindresorhus commented on docs/rules/prefer-number-properties.md
> +# Prefer `Number.{parseInt,parseFloat,isNaN,isFinite}()` and `Number.NaN` over global ones.
```suggestion
# Prefer `Number` static properties over global ones.
```

?

We don't really need to mention all the methods in the title.

2020-03-22 07:11 UTC, sindresorhus commented on docs/rules/prefer-number-properties.md
> +This rule is partly fixable.
Maybe explain why the other are not fixable? Because they have slightly different behavior.

2020-03-22 07:11 UTC, sindresorhus commented on rules/prefer-number-properties.js
> +			// TODO: not sure how this works
I would take a look at TypeScript-ESLint.

https://github.com/typescript-eslint/typescript-eslint/blob/afa7900285ad6d31d2acaff0107fbd19bad4ff06/packages/eslint-plugin-internal/src/rules/prefer-ast-types-enum.ts#L45

2020-03-26 12:44 UTC, merged

2020-03-26 12:44 UTC, sindresorhus commented
Perfect 👌

2026-06-17 12:56 UTC, KyleHorkley commented
Do you think we could add the requirement for `parseFloat` as well? `parseInt` is included here but not `parseFloat`. I know there's the `prefer-number-coercion` rule, but if that's disabled I think it still make sense to include here.

2026-06-17 14:21 UTC, sindresorhus commented
https://github.com/sindresorhus/eslint-plugin-unicorn/pull/3307