`numeric-separators-style`: Add `checkOnlyIfSeparator` option
sindresorhus/eslint-plugin-unicorn pull request #916
Opened 2020-12-05 12:47 UTC by noftaly

Added an option for each literal type, named `checkOnlyIfSeparator`.
As explained in the docs, it:
Check if the group sizes are valid **only** if there are groups, separated with an `_`.

Example:
```js
const foo = 100000; // Pass, because there are no groups, so no check was performed.
const bar = 1_000_000; // Pass, because the group sizes are correct.
const baz = 10_0_000_0; // Fail, because there are groups, but they are incorrect.
```

This option is disabled by default.

Closes #868

2020-12-05 14:44 UTC, fisker commented
I'm not sure if we should add  this option, but you didn't test `12_34.5678e1234.5678`, should we ignore all, or just part?

2020-12-05 15:16 UTC, noftaly commented
Considering it has a separator, I think the entire number should be checked, to be more consistent.

> I'm not sure if we should add this option

No problem, I did not know if I should wait for a "help-wanted" label, so I just did it anyway 😄 Don't hesitate to close the PR if you don't think it should be added.

2021-01-11 11:14 UTC, sindresorhus commented
While I wouldn't personally use this option, I can see how it would be useful if you want to enforce "correctness", but not style.

2021-01-11 11:22 UTC, sindresorhus requested changes

2021-01-11 11:22 UTC, sindresorhus commented on docs/rules/numeric-separators-style.md
> +Type: `boolean`
```suggestion
Type: `boolean`\
Default: `false`
```

2021-01-11 11:22 UTC, sindresorhus commented on docs/rules/numeric-separators-style.md
> +Example:
```suggestion
Example:

```

2021-01-11 11:22 UTC, sindresorhus commented
> Considering it has a separator, I think the entire number should be checked, to be more consistent.

👍

2021-01-18 11:16 UTC, sindresorhus commented
@fisker Are you ok with merging this?

2021-01-18 12:18 UTC, fisker commented
Yes, I'm fine with this, but I think the option can have a better name, like `onlyIfSeparatorExists` or `onlyIfSeparatorPresents`?

And do we want a top level one to easier set for all?

Also, need more tests on different options, and seperator in different position of `1234.5678e1234`

2021-01-18 16:30 UTC, sindresorhus commented
> onlyIfSeparatorExists

👍

2021-01-18 16:31 UTC, sindresorhus commented
Alternatively: `onlyIfContainsSeparator`

2021-01-18 16:32 UTC, sindresorhus commented
> And do we want a top level one to easier set for all?

👍

2021-01-18 16:38 UTC, noftaly commented
> And do we want a top level one to easier set for all?

Just to be sure, do you want only *one* at the top level, or one for each types *and* a "master" setting at the top level that overrides other settings if set?

2021-01-18 16:39 UTC, fisker commented
Both, if top one is set, all default to it.

2021-01-18 16:42 UTC, noftaly commented
> Both, if top one is set, all default to it.

Doesn't it add too many complexity and redundancy. I thought of doing that too but I think it might confuse the user and clutter the options...

2021-01-18 16:47 UTC, fisker commented
```js
{
  onlyIfContainsSeparator: true,
  binary: {
    onlyIfContainsSeparator: false
  }
}
```

Pretty clear to me, think this way you can set `onlyIfContainsSeparator` at  top level, but can be override on each.

2021-01-18 16:48 UTC, noftaly commented
Okay, I'll do that then 👍🏼

2021-01-18 17:08 UTC, noftaly commented
Just curious about the actions, why does the lint errors appear in the build job and not in the lint job? (cf [my last failing commit](https://github.com/sindresorhus/eslint-plugin-unicorn/runs/1722998311)

2021-01-18 17:24 UTC, fisker commented
`lint` is  not really  `lint`, maybewe need rename it, it's `run rules on codebase`, 😄

2021-01-19 02:08 UTC, fisker commented
I changed the logic a little bit, https://github.com/sindresorhus/eslint-plugin-unicorn/pull/916/commits/ebf5aeee6f8e3054e0a0bd6681bdb76c853a8afd, I think this is more reasonable.

2021-01-19 08:15 UTC, merged