Add `prefer-regexp-test` rule
sindresorhus/eslint-plugin-unicorn pull request #970
Opened 2020-12-30 04:53 UTC by fisker

Fixes #732

2020-12-31 23:42 UTC, sindresorhus requested changes

2020-12-31 23:42 UTC, sindresorhus commented on rules/prefer-regexp-test.js
> +			if (isBooleanNode(node)) {
I would do an early-return here too.

2020-12-31 23:42 UTC, sindresorhus commented on rules/prefer-regexp-test.js
> +					// All nodes pass `isBooleanNode` can't have ASI problem
```suggestion
					// The nodes that pass `isBooleanNode` cannot have an ASI problem.
```

2020-12-31 23:42 UTC, sindresorhus commented
This is not waiting for https://github.com/sindresorhus/eslint-plugin-unicorn/pull/976, right?

2021-01-02 00:22 UTC, fisker commented
> This is not waiting for #976, right?

Current implementation not relay on #976, but better swith to the utility I'm going to add in #976 before merge.

2021-01-06 12:24 UTC, sindresorhus commented
> but better swith to that utility I'm going to add in #976 before merge.

👍

2021-01-08 08:19 UTC, sindresorhus commented
Tests are failing.

2021-01-08 10:28 UTC, fisker commented
Fixed.

2021-01-08 10:30 UTC, merged